set nocompatible

filetype on
filetype plugin on
filetype indent on

syntax on

let mapleader = " "

" plugins

call plug#begin('~/.vim/plugged')
  Plug 'vim-airline/vim-airline'
  Plug 'scrooloose/nerdtree'
  Plug 'mg979/vim-visual-multi', {'branch': 'master'}
  Plug 'tpope/vim-commentary'
  Plug 'tpope/vim-fugitive'
  Plug 'neoclide/coc.nvim'
call plug#end()

autocmd Filetype html setlocal tabstop=2 shiftwidth=2 expandtab
autocmd Filetype vim setlocal tabstop=2 shiftwidth=2 expandtab

colorscheme slate
set background=dark

highlight CursorLine ctermbg=black guibg=#222222
highlight CursorColumn ctermbg=black guibg=#222222

so ~/.vim/settings.vim
so ~/.vim/mappings.vim
so ~/.vim/coc.vim
