--------------------------------------------------------------------------------
-- Command playground
--------------------------------------------------------------------------------

-- vim.api.nvim_create_user_command('CopyPath',
--     function(opts)
--     end,
--     {
--         -- '*' means 0 or more arguments
--         -- '+' means 1 or more
--         -- '1' means exactly 1
--         nargs = '*',
--         complete = function()
--             return { 'filename', 'relative', 'absolute' }
--         end,
--         desc = 'Playing with user commands',
--     }
-- )
