require("core.plugins_config.treesitter-config")
require("core.plugins_config.lsp-config")

-- plugins

require("core.plugins_config.rainbow-delimiters")
require("core.plugins_config.symbols-outline")
require("core.plugins_config.neovim-project")
require("core.plugins_config.close-buffers")
require("core.plugins_config.todo-comments")
require("core.plugins_config.noice-config")
require("core.plugins_config.smart-split")
require("core.plugins_config.kommentary")
require("core.plugins_config.bufferline")
require("core.plugins_config.toggleterm")
-- require("core.plugins_config.persisted")
require("core.plugins_config.autopairs")
require("core.plugins_config.telescope")
require("core.plugins_config.auto-save")
require("core.plugins_config.cinnamon")
require("core.plugins_config.gitsigns")
require("core.plugins_config.vim-test")
require("core.plugins_config.phpactor")
require("core.plugins_config.zen-mode")
require("core.plugins_config.nvim-cmp")
require("core.plugins_config.lua-snip")
require("core.plugins_config.incline")
require("core.plugins_config.lualine")
require("core.plugins_config.murmur")
require("core.plugins_config.neogit")
-- require("core.plugins_config.focus")
require("core.plugins_config.navic")
require("core.plugins_config.flash")
require("core.plugins_config.ufo")
