require("core.plugins_config.treesitter-config")
require("core.plugins_config.lsp-config")

-- themes
require("core.plugins_config.kanagawa-theme")
require("core.plugins_config.monokai-pro")
require("core.plugins_config.everforest")

-- feline themes
-- require("core.plugins_config.feline-one-monokai")
require("core.plugins_config.feline-dharmux")
-- require("core.plugins_config.lua-line")

require("core.plugins_config.symbols-outline")
require("core.plugins_config.close-buffers")
require("core.plugins_config.kommentary")
require("core.plugins_config.bufferline")
require("core.plugins_config.toggleterm")
require("core.plugins_config.persisted")
require("core.plugins_config.autopairs")
require("core.plugins_config.neoscroll")
require("core.plugins_config.telescope")
require("core.plugins_config.gitsigns")
require("core.plugins_config.fugitive")
require("core.plugins_config.vim-test")
require("core.plugins_config.phpactor")
require("core.plugins_config.true-zen")
require("core.plugins_config.nullls")
require("core.plugins_config.murmur")
require("core.plugins_config.focus")
require("core.plugins_config.marks")
require("core.plugins_config.tmux")
require("core.plugins_config.hop")
require("core.plugins_config.ufo")
