return {
  {
    "hedyhli/outline.nvim",
    lazy = true,
    cmd = { "Outline", "OutlineOpen" },
    keys = {
      { "<leader>o", "<cmd>Outline<CR>", desc = "Toggle outline" },
    },
    opts = {
      keymaps = {
        show_help = "?",
        close = { "<Esc>", "q" },
        goto_location = "<Cr>",
        peek_location = "o",
        goto_and_close = "<S-Cr>",
        restore_location = "<C-g>",
        hover_symbol = "<C-space>",
        toggle_preview = "P",
        rename_symbol = "r",
        code_actions = "a",
        fold = "h",
        unfold = "l",
        fold_toggle = "<Tab>",
        fold_toggle_all = "<S-Tab>",
        fold_all = "W",
        unfold_all = "E",
        fold_reset = "R",
        down_and_jump = "<C-j>",
        up_and_jump = "<C-k>",
      },
    },
  },
  {
    "dnlhc/glance.nvim",
    config = true,
    lazy = true,
    cmd = "Glance",
    keys = {
      { "gD", "<CMD>Glance definitions<CR>", desc = "Glance definitions" },
      { "gl", "<CMD>Glance references<CR>", desc = "Glance references" },
      { "gM", "<CMD>Glance implementations<CR>", desc = "Glance implementations" },
      -- { "gY",  "<CMD>Glance type_definitions<CR>", desc = "Glance type definitions" },
    },
  },
}
